name: Mon Application CI
on: [push, pull_request]

permissions:
  contents: read
  packages: write

jobs:
  platform-ci:
    # On appelle le workflow situé dans le même dépôt
    uses: ./.github/workflows/ci-reusable.yml
